### ISSUE TITLE
Document milestone 2 (application status)

### ISSUE THREAD

**Issue by DuplosFidibuss** [DuplosFidibuss/academic-time-planner#81]
- [ ] Describe synchronization approach and unit tests in methods.
- [ ] Describe status display in results.
- [ ] Describe Moq in fundamentals.
